version: "3.9"

services:

  frontend:
    build: ./frontend/ui-ux
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - genai
      - machine_learning
    env_file:
      - ./backend/.env
    restart: always

  genai:
    build: ./backend/ML_Backend/GenAI
    container_name: GenAI
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: always

  machine_learning:
    build: ./backend/ML_Backend/Machine_learning
    container_name: Machine_learning
    ports:
      - "5000:5000"
    restart: always

  # node-backend:
  #   build: ./backend
  #   container_name: node-backend
  #   ports:
  #     - "5002:5002"
  #   restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - genai
      - machine_learning

    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    restart: always