global:
  scrape_interval: 5s

scrape_configs:

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # ML Backend Metrics
  - job_name: "ml-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["ml-backend:5002"]

  # GenAI Backend Metrics
  - job_name: "genai-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["genai-backend:5003"]