global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "machine_learning"
    metrics_path: /metrics
    static_configs:
      - targets: ["machine_learning:5000"]

  - job_name: "genai"
    metrics_path: /metrics
    static_configs:
      - targets: ["genai:5001"]